### ISSUE TITLE
sqlflush does not work without wagtail.contrib.wagtailsearchpromotions installed

### ISSUE THREAD

**Issue by timheap** [torchbox/wagtail#2217] opened 2016-02-10 00:16 UTC
Trying to run `sqlflush` on a default Wagtail install, running on Postgres, without wagtailsearchpromotions installed, leads to database errors. The `wagtailsearch_editorspick` table has a foreign key to `wagtailcore_page`. As `wagtailsearch_editorspick` is controlled by `wagtailsearchpromotions`, which is not installed, `sqlflush` does not generate a TRUNCTATE statement for it. Postgres refuses to truncate a table referenced by a foreign key from a table not included in the TRUNCATE statement.

Steps to reproduce:

* Make a new wagtail project: `wagtail start flush`

* Configure the application to use a Postgres database

* Migrate the DB to create the tables, and then try to empty them:
    ```shell
$ ./manage.py migrate
$ ./manage.py sqlflush | ./manage.py dbshell
BEGIN
ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "wagtailsearch_editorspick" references "wagtailcore_page".
HINT:  Truncate table "wagtailsearch_editorspick" at the same time, or use TRUNCATE ... CASCADE.
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
# ... snip ...
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

Adding `wagtailsearchpromotions` to `INSTALLED_APPS` fixes this, but considering I never added it to `INSTALLED_APPS` in the first place, this is confusing.

**Comment by gasman** [comment] 2016-02-10 09:25
Duplicate of #1824

**Closed by gasman** 2016-02-10 09:25 UTC
