### ISSUE TITLE
[Feature] Sitemap display name.

### ISSUE THREAD

**Issue by SalahAdDin** [torchbox/wagtail#1346] opened 2015-05-26 07:45 UTC
I consider that thiw will be very useful. Now i needing get the site display name for a template, i can't getting through a context processor, so, i make a template time for get_site_name, but, site don't have name and host name don't works for me.

Thank you for your help.

**Comment by davecranwell** [comment] 2015-06-10 15:47
I believe this is a duplicate of: https://github.com/torchbox/wagtail/issues/1194

**Closed by davecranwell** 2015-06-10 15:47 UTC
