### ISSUE TITLE
Add variable resolvement to "image" template tag

### ISSUE THREAD

**Issue by diveru4i** [torchbox/wagtail#2182] opened 2016-02-01 10:37 UTC
It would be super useful to allow us to pack image formats into variables.

For example:
```python
## models.py
class Banner(Model):
    SIZES = [
        ('fill-200x200', 'small'),
        ('fill-400x400', 'big'),
    ]
    image = ForeignKey(Image)
    size = CharField(choices=SIZES)
```

```django
{# template.html #}
{% image banner.image banner.size %}
```

Hacked solution:
```python
## wagtailimages_tags.py
class ImageNode(template.Node):
    ...
    def render(self, context):
        try:
            self.filter_spec = template.Variable(self.filter_spec).resolve(context)
        except template.VariableDoesNotExist:
            pass
        ...

**Comment by gasman** [comment] 2016-02-01 10:41
Duplicate of #2090

**Closed by gasman** 2016-02-01 10:41 UTC

**Comment by kaedroho** [comment] 2016-02-01 10:53
@diveru4i I was thinking about this idea I call "filter-spec macros" which I think might help with this.

You can add your own filter specs to Wagtail using the ``register_image_operations`` hook: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/wagtail_hooks.py#L69-L77. "macros" would allow you to build filter specs from others and use them in your template:

```python
@hooks.register('register_image_operations')
def register_image_operations():
    return [
        ('banner_small': MacroOperation(r'^$', 'fill-200x200'),
        ('banner_big': MacroOperation(r'^$', 'fill-400x400'),
    ]
```

Then in the template: ``{% image myimage banner_big %}``

Just to describe the idea, here's an example which has parameters (example from #1694):

```python
@hooks.register('register_image_operations')
def register_image_operations():
    return [
        ('pad_with_bg': MacroOperation(r'^(\d+)-(\d+)-([0-9a-f){6}$', 'pad-{0}-{1} bg-{3}'),
    ]
```
