### ISSUE TITLE
Not able to save a single tag with multiple words in it

### ISSUE THREAD

**Issue by sbast** [torchbox/wagtail#824] opened 2014-11-19 14:37 UTC
When you use Tagging feature for Pages (as in http://wagtail.readthedocs.org/en/v0.8.3/core_components/pages/model_recipes.html#tagging) you can't save a page with only a single tag containing multiple words in it.

Steps to reproduce:
1. Start editing a page in Wagtail admin.
2. Ensure tags field is empty.
2. Start typing a single tag with a double quote and enter multiple words, then close it with double quote.
3. Save the page.
4. Edit the page again—you will see multiple tags instead a one with multiple words.

The problem is with tag-it.js which doesn't put a comma after a single tag (neither double quotes it by default) when POSTing to Wagtail so django-taggit treats it as multiple tags.

Fix is coming soon with a pull request from Tivix team.

**Comment by dchaplinsky** [comment] 2015-07-22 22:07
Seems that this is broken again.

I wonder if you should set allowSpaces to true in tagit plugin config?

**Comment by dchaplinsky** [comment] 2015-07-23 08:31
To not to hotpatch existing version I've ended up with this class:

```
class AdminMultiTagWidget(widgets.AdminTagWidget):
    def render_js_init(self, id_, name, value):
        return "$('#' + {0}).tagit({{autocomplete: {{source: {1}}}, allowSpaces: true}});".format(
            json.dumps(id_),
            json.dumps(reverse('wagtailadmin_tag_autocomplete')))
```

And it nailed it.

**Comment by gasman** [comment] 2015-10-26 17:51
@dchaplinsky This is working for me on the current version when I follow the exact steps given by @sbast. Are you doing the same, or something different?

Personally I'm against setting `allowSpaces: true` - it breaks the "classic" tagging behaviour of being able to enter lots of single-word tags quickly as a space-separated list.

**Comment by gasman** [comment] 2015-10-29 00:18
Re-closing, as I can't reproduce the problem as stated on the current version - please reopen if you have more info on how to reproduce.

**Closed by gasman** 2015-10-29 00:18 UTC
Labels: Needs info
