### ISSUE TITLE
StreamField not saving after update to 1.6.2

### ISSUE THREAD

**Issue by creativedutchmen** [torchbox/wagtail#2994] opened 2016-09-13 09:35 UTC
After updating to 1.6.2, StreamFields are no longer saving.

There are no errors in the INFO log, and everything looks normal - the green message is displayed as always, and a new revision is created with all the updated fields. Except the StreamField.

**Comment by gasman** [comment] 2016-09-13 12:00
Replied at https://groups.google.com/d/msg/wagtail/FPi4GDxDQvU/jmj6lcfDAQAJ - closing here as I'm unable to reproduce this as a Wagtail bug with the information given.

**Comment by creativedutchmen** [comment] 2016-09-13 13:13
I've created a very [basic demo](https://github.com/creativedutchmen/wagtail_issue_demo) which inhibits the behaviour. To see what I mean, create a new page, and use the StreamField to create a heading. Then save, and watch as the heading is removed from the body.

**Comment by gasman** [comment] 2016-09-13 13:18
Thanks! I can confirm that I'm seeing the issue on your demo project.

**Comment by gasman** [comment] 2016-09-13 14:03
Looks like this is a regression in Django 1.10.1, caused by this commit: https://github.com/django/django/commit/325dd0befea3012c42eefa061f509fbdf1b6a8aa

(As a temporary workaround, then, downgrading to Django 1.10 should hopefully solve this.)

**Comment by gasman** [comment] 2016-09-13 14:48
The commit above was designed to change Django's behaviour when a ModelForm is submitted with one of its fields missing from the submission, and that field has a default value. Discussion here: https://groups.google.com/d/msg/django-developers/lpfM6QPILoQ/9mOXrtRWCwAJ

The problem here arises because Django is using some dubious logic to determine whether the field is missing from the form data: it assumes that there should always be an HTML form input that matches the Django field name. This isn't the case for StreamField, which consists of many form inputs (with names like `body-0-type`, `body-0-value` rather than a single `body` field).

If I'm not mistaken, this assumption is _also_ incorrect for some of Django's own widgets, such as [SelectDateWidget](https://docs.djangoproject.com/en/1.10/ref/forms/widgets/#selectdatewidget), which would mean that this is a genuine Django bug, rather than StreamField doing something unsupported. I'll do some further investigation, and open this as a Django issue if appropriate.

**Comment by creativedutchmen** [comment] 2016-09-13 15:15
Thank you very much for the thorough investigation, downgrading tot 1.10 did indeed fix the problem.

**Comment by gasman** [comment] 2016-09-13 15:52
Sweet, looks like Django already has a fix for this in the pipeline: https://code.djangoproject.com/ticket/27186

Looking at [the related PR](https://github.com/django/django/pull/7217), it looks like we'll need to make a Wagtail 1.6.3 bugfix release that defines the `value_omitted_from_data` method on StreamField's BlockWidget.

**Closed** 2016-09-30 09:12 UTC
Labels: component:Streamfield, Release blocker, type:Bug
