### ISSUE TITLE
Improvements to forms UI

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#778] opened 2014-11-03 11:18 UTC
Currently there is no way to remove a specific entry from a forms database from within Wagtail. As a quickfix I would suggest a small trash icon next to each line but ultimately batch actions would be useful.

**Comment by kaedroho** [comment] 2015-07-19 19:37
Closing as duplicate of #1190

**Closed by kaedroho** 2015-07-19 19:37 UTC
Labels: Enhancement
