### ISSUE TITLE
Copy function regression with many to many fields

### ISSUE THREAD

**Issue by bufke** [torchbox/wagtail#1852] opened 2015-10-21 18:23 UTC
This seems to have popped up in 1.1. It didn't happen before.

There seems to be a few ways to reproduce. Happens on [wagtail blog](https://github.com/thelabnyc/wagtail_blog/). Check out the project. Create a Blog Index Page and Blog Page. Attempt to copy the blog page.

If you remove these two lines the error goes away. Inspecting the kwargs in the stack trace shows which fields are troublesome. [categories M2M field](https://github.com/thelabnyc/wagtail_blog/blob/master/blog/models.py#L199) and [tags ClusterTaggableManager](https://github.com/thelabnyc/wagtail_blog/blob/master/blog/models.py#L173)

Another way I found to reproduce is by adding a project like `django-notifications` that has generic foreign keys. I haven't explored what's going on here as much. 

```
Traceback:
File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.4/site-packages/django/views/decorators/cache.py" in _cache_controlled
  43.             response = viewfunc(request, *args, **kw)
File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/wagtail/wagtailadmin/views/pages.py" in copy
  638.                 user=request.user,
File "/usr/local/lib/python3.4/site-packages/wagtail/wagtailcore/models.py" in copy
  810.         page_copy = self.specific_class(**specific_dict)
File "/usr/local/lib/python3.4/site-packages/wagtail/wagtailcore/models.py" in __init__
  325.         super(Page, self).__init__(*args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/modelcluster/models.py" in __init__
  177.             super(ClusterableModel, self).__init__(*args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py" in __init__
  480.                 raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])

Exception Type: TypeError at /admin/pages/4/copy/
Exception Value: 'blog_categories' is an invalid keyword argument for this function
```

Here is a internal project that has the same issue but more "bad" kwargs

/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 480
```
>>> kwargs
{'tags': <modelcluster.contrib.taggit._ClusterTaggableManager object at 0x7f6aa24adef0>, 'target_actions': <django.contrib.contenttypes.fields.create_generic_related_manager.<locals>.GenericRelatedObjectManager object at 0x7f6aa24b17b8>, 'action_object_actions': <django.contrib.contenttypes.fields.create_generic_related_manager.<locals>.GenericRelatedObjectManager object at 0x7f6aa24b1550>, 'blog_categories': <django.db.models.fields.related.create_many_related_manager.<locals>.ManyRelatedManager object at 0x7f6aa24b1780>, 'actor_actions': <django.contrib.contenttypes.fields.create_generic_related_manager.<locals>.GenericRelatedObjectManager object at 0x7f6aa24b1ac8>  }
```

Lots of bad kwargs. Seems like any ManyToMany or GenericRelatedObjectManager causes it.

**Comment by gasman** [comment] 2015-10-27 12:47
Presumably this was triggered by #1660. Note that we don't formally support M2M relations (other than ClusterTaggableManager) since django-modelcluster doesn't currently implement them - the likely effect of this is that previews and saved drafts will show the live database state of those objects rather than the updated ones.

However, it would be good for us to avoid regressions where they *are* being used - will investigate further.

**Comment by gasman** [comment] 2015-10-29 15:06
Have implemented a fix for M2M and tag fields in #1879. I also added a basic test for generic foreign keys in that PR, but wasn't able to reproduce any error on that - please open a new ticket if you're able to track down any failures with generic foreign keys that aren't fixed by this PR.

**Comment by bufke** [comment] 2015-10-29 17:56
Taking a look now - is some some change in that branch that would cause compressor.exceptions.UncompressableFileError: 'wagtailadmin/css/normalize.css'

**Comment by bufke** [comment] 2015-10-29 18:00
Testing it by only sending POST requests to bypass compressor. 

This fixes some but not all issues. My kwargs is now

{'actor_actions': <django.contrib.contenttypes.fields.create_generic_related_manager.<locals>.GenericRelatedObjectManager object at 0x7f6775b51320>, 'action_object_actions': <django.contrib.contenttypes.fields.create_generic_related_manager.<locals>.GenericRelatedObjectManager object at 0x7f6775b780f0>, 'target_actions': <django.contrib.contenttypes.fields.create_generic_related_manager.<locals>.GenericRelatedObjectManager object at 0x7f6775b78048>}

I'll keep investigating and see if I can come up with a unit test or something easy to reproduce

**Comment by gasman** [comment] 2015-10-29 18:30
UncompressableFileError means that you need to set up the node.js/npm build toolchain, as detailed here: http://docs.wagtail.io/en/latest/contributing/developing.html

**Comment by bufke** [comment] 2015-10-29 18:58
Looks like we would have to do another if statement to keep GenericForeignKey's from getting into specific_dict. Is there any reason we'd ever want it in there?

>>> field
<django.contrib.contenttypes.fields.GenericRelation: action_object_actions>

I can work on a failing without change unit test. How's the workflow go on a change to a pull request?

**Comment by gasman** [comment] 2015-10-29 19:36
Do you have any reason to believe that the GenericForeignKeys in specific_dict are doing any harm? It looks like Django is happy to accept them in the `self.specific_class` constructor - they may be redundant, because they're just duplicating the information from the content_type and object_id fields, but I don't think that causes any problem.

You can commit changes to this branch, push it to your fork of Wagtail and then submit it as a new pull request to torchbox/wagtail:master (which will then contain both my commits and yours) - alternatively you can submit it as a pull request to gasman/wagtail:fix/copy-page-with-m2m so that it gets merged into my pull request. (I think the first way is better in this case, though - the GFK fix is a distinct issue from the M2M fix, so it makes sense for it to be a new PR.)

**Comment by bufke** [comment] 2015-10-29 19:42
It gives me the same `TypeError: 'action_object_actions' is an invalid keyword argument for this function`. It's from djagno-activity-stream which has a GFK which can reference a Page. I got the test working so now I just need to reproduce it without having all of activity stream installed.

**Comment by bufke** [comment] 2015-10-29 19:58
Narrowed it down to the registry in django-activity-stream. Sounds like the bug exists there and not in wagtail. The other issue appears fixed so thanks!

**Comment by bufke** [comment] 2015-10-29 20:22
Just some FYI follow up - I think the way Activity Stream's register function works should be setting field.auto_created to True but doesn't. So clearly a Activity Stream issue. Worked around is posted on the above reference to an issue in activity stream.

**Closed** 2015-11-02 10:50 UTC
Labels: Bug
