### ISSUE TITLE
Wagtail page objects loose their child count when moving / deleting their child pages under certain conditions.

### ISSUE THREAD

**Issue by HitDaCa** [torchbox/wagtail#1655] opened 2015-08-31 23:56 UTC
Situation for issue reproduction:
A wagtail page object "PageClassX" (published), which inherits from an abstract wagtail page object "AbstractPageClassA", has multiple child objects. Each of these child-objects is of type "PageClassY" and inherit from the same "AbstractPageClassA".
A number of these child pages ("PageClassY") are existent and published.

If we now try to delete a "PageClassY" child page or move it to different parent page object "PageClassZ" , which also inherits from "AbstractPageClassA", the initial page object "PageClassX" will loose its child count (table: wagtailcore_page, field: numchild) and gets set to 0.

This leads to the "editor/user" suddenly "loosing" all of his subpages in the explorer. From that point forward, it is also not possible to manually navigate to the "subpages listing overview" of the affected page object or add any further subpages to the affected page object.

Is there any way to stop this happening?

**Comment by gasman** [comment] 2015-10-30 12:09
Hi @HitDaCa - thanks for the detailed report! Afraid I'm not able to reproduce this on either Wagtail 1.1 or current master, though - I'm using the following `home/models.py` on a fresh `wagtail start` project (tested with sqlite and postgresql):

    from __future__ import unicode_literals

    from django.db import models

    from wagtail.wagtailcore.models import Page
    from wagtail.wagtailadmin.edit_handlers import FieldPanel


    class HomePage(Page):
        pass

    class AbstractPageClassA(Page):
        subtitle = models.CharField(blank=True, max_length=255)

        content_panels = Page.content_panels + [
            FieldPanel('subtitle'),
        ]

        class Meta:
            abstract = True

    class PageClassX(AbstractPageClassA):
        body = models.TextField(blank=True)

        content_panels = AbstractPageClassA.content_panels + [
            FieldPanel('body'),
        ]

    class PageClassY(AbstractPageClassA):
        body = models.TextField(blank=True)

        content_panels = AbstractPageClassA.content_panels + [
            FieldPanel('body'),
        ]

    class PageClassZ(AbstractPageClassA):
        body = models.TextField(blank=True)

        content_panels = AbstractPageClassA.content_panels + [
            FieldPanel('body'),
        ]

Within the admin, I perform these steps:

* create and publish a page of type PageClassX, as a child of the homepage, with the title 'pcx'
* create and publish two pages of type PageClassY as children of pcx, named 'pcy1' and 'pcy2'
* create and publish a page of type PageClassZ, as a child of the homepage, with the title 'pcz'
* move the page 'pcy1' from 'pcx' into 'pcz'

After this, all pages still appear on the admin listing pages as expected, and in the database 'pcx' and 'pcz' both have numchild=1. Are you able to reproduce this issue on a test setup like this - if so, what do I need to change?

**Comment by gasman** [comment] 2015-11-02 12:36
Closing as unable to replicate - please reopen if you can provide steps for reproducing this bug.

**Closed by gasman** 2015-11-02 12:36 UTC
Labels: Bug, Needs info
