### ISSUE TITLE
Block names of StructBlock are not properly displayed 

### ISSUE THREAD

**Issue by kidlj** [torchbox/wagtail#1369] opened 2015-06-04 05:21 UTC
v1.0b2

The Wagtail code:

``` Python
class HomePage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full")),
        ('carousel', ListBlock(
            StructBlock([
                ('image', ImageChooserBlock()),
                ('page', PageChooserBlock()),
                ('quotation', TextBlock()),
            ]), icon='cogs', template='shop/blocks/carousel.html')),
    ])
```
I get the following editing interface:

![streamfield_label](https://cloud.githubusercontent.com/assets/300616/7977313/12375392-0abc-11e5-8d0f-c79b2d61cdbb.png)

Note that the *image* and *quotation* block names are not displayed as block *page* does.

**Comment by SalahAdDin** [comment] 2015-06-04 06:20
Wow, these can we do?

**Comment by gasman** [comment] 2015-06-04 08:27
Duplicate of #1118

**Closed by gasman** 2015-06-04 08:27 UTC

**Comment by SalahAdDin** [comment] 2015-06-04 15:17
Really? That Can Be Done ?

**Comment by kidlj** [comment] 2015-06-05 07:49
@SalahAdDin Yes, this can be done.

Except for this issue, I neither don't know how to access the chosen page's attributes in `shop/blocks/carousel.html` template.

What I can do right now in `shop/blocks/carousel.html` template:

```python
{% for item in self %}
  <a href="{{ item.page.url }}">
      {% image item.image width-400 %}
      {{ item.quotation }}
  </a>
{% endfor %}
```
This works.

But I can't access more attributes of the chosen page object, for example `{{ item.page.cover }}` or `{{ item.page.intro }}`. Any further idea or am I using StreamField in the wrong way?

**Comment by gasman** [comment] 2015-06-05 09:00
Answered on the Google group - https://groups.google.com/d/msg/wagtail/E2yV4WoLAAs/DeYm3tFsVasJ

**Comment by kidlj** [comment] 2015-06-05 09:12
@gasman Thank you Matt.

**Comment by SalahAdDin** [comment] 2015-06-06 02:02
@kidlj Works it?

**Comment by kidlj** [comment] 2015-06-06 07:21
@SalahAdDin Yes, it works.

**Comment by DevinCalado** [comment] 2016-10-01 23:57
This topic is over a year old, but I can't figure out how to get the below suggestion to work...

> This is failing because the PageChooserBlock only returns a plain Page instance, which doesn't include the additional intro/body fields from ItemPage. You can convert the Page instance to an instance of ItemPage (at the cost of an extra database query) by accessing {{ item.page.specific }}. 

```
{% for item in self.products_a %}
  <div class="column">
    <img class="thumbnail" src="http://placehold.it/300x400">
    <h5>{{ item }}</h5>
    <p>{{ item.page.specific.price }}</p>
    <p>{{ item.page.price}}</p>
    <a href="#" class="button expanded">Buy</a>
  </div>
{% endfor %}
```
I'm not having any luck trying to get the Product page properties.  The only property I can access is` {{ item }}`.  What do I need to do to access the specific page properties?

Any tips on this would be greatly appreciated.

**Comment by gasman** [comment] 2016-10-02 07:52
Hi @DevinCalado - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.
