### ISSUE TITLE
StreamField widget does not work when used in a related model

### ISSUE THREAD

**Issue by Gagaro** [torchbox/wagtail#2653] opened 2016-05-31 14:33 UTC
I tried to use a StreamField in a Orderable model and I have a few issue. My code is as following:

```python
class HomePage(Page):
    content_panels = Page.content_panels + [
        StreamFieldPanel('test'),
        InlinePanel('blocks', label="Blocks")
    ]


class HomePageBlock(Orderable):
    page = ParentalKey(HomePage, related_name='blocks')

    block = StreamField([
        ('heading', blocks.CharBlock()),
        ('paragraph', blocks.RichTextBlock()),
        ('carousel', blocks.ListBlock(ImageChooserBlock())),
    ])

    panels = [
        StreamFieldPanel('block')
    ]

```

Edit: I clicked the wrong button, let me edit the issue...

**Comment by gasman** [comment] 2016-05-31 14:35
Duplicate of #1735

**Comment by Gagaro** [comment] 2016-05-31 14:36
Thanks, I looked it up before opening this one but missed it.

**Closed by gasman** 2016-05-31 14:35 UTC
