### ISSUE TITLE
Add Gmail Actions to notification emails

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#662] opened 2014-10-01 08:44 UTC
Wagtail's emails should be changed to multipart HTML/plain-text, to benefit from styling improvements and also Gmail Actions https://developers.google.com/gmail/actions/

**Comment by gasman** [comment] 2016-02-17 16:10
Ticket title updated so that Gmail Actions and HTML emails can be treated as two distinct tasks, rather than #2245 being an almost-but-not-quite-duplicate of this ticket...

(in other words: #2245 is a prerequisite for this.)

**Comment by mikedingjan** [comment] 2016-06-16 14:49
I think it's wise not to implement this in the wagtail codebase, GMail actions require a registration which has a pretty complicated and strict approval process 

https://developers.google.com/gmail/markup/registering-with-google

Because the notifications are now in HTML this can already be implemented in projects by overriding the templates.

**Comment by gasman** [comment] 2016-06-16 14:51
Makes sense to me. Thanks for investigating, @mikedingjan!

**Closed by gasman** 2016-06-16 14:51 UTC
Labels: component:Frontend, difficulty:Easy, size:Small, type:Enhancement
