### ISSUE TITLE
References to base page model in WT code make overriding difficult

### ISSUE THREAD

**Issue by ajdegol** [torchbox/wagtail#2022] opened 2015-12-09 16:18 UTC
We're writing our own permissions logic in order to allow for specific moderators on individual pages. To do this we're using a subclass of the Page model. This would be fine, except that there are instances in the codebase that refer to the base class instead of using specific. e.g:
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/views/pages.py#L729

At present we're overriding the __getattribute__ on PageRevision to return page.specific when requesting page, in order to get round the issue.

**Comment by chimeno** [comment] 2015-12-09 19:15
I guess something link ``get_user_model()`` in the same way django does with authentication is a good way to get the main 'page' base class.

**Comment by ajdegol** [comment] 2015-12-10 11:04
Interesting thought, though if you had multiple derived pages with different permissions models that may be difficult to specify.

**Comment by gasman** [comment] 2015-12-11 10:38
The `get_page_model` approach (covered by #836) would be the one I'd favour here. I suspect that allowing permission logic to be overridden on a per-page-type basis could get messy very quickly:

* firstly, on listings pages (e.g. the explorer listing, where we need to check permissions to determine which action buttons to display), we'd need to instantiate each page as its most specific class, just in case it had custom permission rules - which could be quite a hefty database hit;
* secondly, permission rules will often require considering interactions between multiple pages (e.g. 'can move page X to parent Y') which gets much more complicated to define and implement if there's a chance that they're working by different rules. (We had a hint of this in #1572 with `parent_page_types` / `subpage_types`, and it's not something I'd want to repeat more widely throughout the design of Wagtail!)

**Comment by ajdegol** [comment] 2015-12-11 12:11
After some thought and discussion that solution could be made to work with our use case.

**Comment by gasman** [comment] 2015-12-11 13:36
Good to know - will close this as a duplicate of #836 then.

**Closed by gasman** 2015-12-11 13:36 UTC
