### ISSUE TITLE
Required fields on custom image model breaks uploads

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#2487] opened 2016-04-18 13:26 UTC
I have a custom image model:

```python
class ImageWithAttribution(AbstractImage):
    attribution = models.CharField(max_length=255, blank=True, null=True)
    alt_text = models.CharField(max_length=255, null=True)
    caption = models.CharField(max_length=255, null=True)

    admin_form_fields = Image.admin_form_fields + (
        'attribution',
        'alt_text',
        'caption',
    )

    @property
    def full_url(self):
        return self.get_rendition('original').url
```

I am trying to make blank=False for alt_text and caption (i.e make them mandatory from the front end), but uploads immediately fail.

![images](https://cloud.githubusercontent.com/assets/11830393/14605658/e3f6dca0-0579-11e6-8817-84147a0d84ef.png)

**Comment by gasman** [comment] 2016-04-18 13:32
Duplicate of #847

**Closed by gasman** 2016-04-18 13:32 UTC

**Comment by lee-kagiso** [comment] 2016-04-18 13:37
Oops sorry, github search didn't bring this up...

**Comment by lee-kagiso** [comment] 2016-04-18 13:42
In fact something might be materially different, my model is not making the fields non-null at the db level, so is there reason why an upload can't be done prior to showing the edit image form, which then enforces the non-blank constraint?

**Comment by gasman** [comment] 2016-04-18 14:13
That's basically what I suggested in my comment on the other ticket:

> Alternatively, it might be possible to come up with a mechanism where the required fields aren't enforced at the database level

I should really have written "enforced at the database *or model* level". `null=True` means that there's no constraint at the database level, but Django will still apply the `blank=False` validation when we call `image.save()` during the initial upload, and refuse to create the record. To address that, we'd need to keep all validation out of the model definition, and just apply it in the form instead (https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/views/multiple.py#L24-L34).
