### ISSUE TITLE
Add ability to edit links in rich text editor

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#444] opened 2014-07-09 10:10 UTC
Currently, to edit a link you must remove it and create a new one.

Clicking the link icon while you have a link selected should reopen the link modal allowing the user to change the link without having to remove it first.

**Comment by tmsndrs** [comment] 2015-07-23 14:14
![wagtail_link_workflow 1](https://cloud.githubusercontent.com/assets/7290588/8852472/5ebd05d8-314d-11e5-812b-b2ddc17e8e76.gif)

**Comment by SalahAdDin** [comment] 2015-07-23 19:48
:+1:

**Comment by lee-kagiso** [comment] 2015-09-29 07:26
Also, as per #1547 there is no way currently to know where the link leads to, so maybe on hover it could show the url?

**Comment by bbusenius** [comment] 2016-02-18 17:43
Yes, not seeing the url has been a trouble spot for our users as well. Often they break the link when they're only trying to see what it was linked to in the first place. The problem is made worse by the fact that the undo/revert button doesn't bring the link back. The overall link workflow has been a pain point for our web authors, especially when they've been migrating large quantities of content from the old CMS to wagtail.

**Comment by JoshBarr** [comment] 2016-03-17 21:47
I'm making some progress on this, but I 100% believe that resolving this issue means moving away from Hallo.js as the default editor in Wagtail.

**Comment by SalahAdDin** [comment] 2016-03-17 23:35
:+1:

**Comment by ababic** [comment] 2016-05-24 15:23
Hi guys! Below are a couple of minor things I've noticed with the new link editor functionality in `1.5rc1`...

1. If you edit a link that currently links to a page, the link editor interface knows about target page, but doesn't display the title of the target page anywhere... you can only see a breadcrumb of it's ancestors.
2. Again, if you edit a link that currently links to a page, then click 'External link' or 'Email link' , then `Internal page` again, the interface seems to forget the target page.

**Comment by gasman** [comment] 2016-05-24 15:34
Hi @ababic - please can you create these as new tickets? It's easier to track progress on fixing them if they're entered as separate tickets, rather than just a follow-up comment here. (This one should really have been closed after #2417 was merged - sorry for the confusion!)

**Closed by gasman** 2016-05-24 15:34 UTC
Labels: Enhancement
