### ISSUE TITLE
Moving a page to where it's not allowed is possible

### ISSUE THREAD

**Issue by creativedutchmen** [torchbox/wagtail#1636] opened 2015-08-23 19:21 UTC
It's possible to limit the types of subpages and parent pages when creating a Page by using the `subpage_types` and `parent_page_types` properties.
In general, these settings are respected by Wagtail, except when moving a page.

For instance, it is possible to have an Article page, which does not allow any child pages (subpage_types is an empty list), but when another Article is moved, the other articles are selectable as parent.

**Comment by gasman** [comment] 2015-08-23 19:29
Duplicate of #638

**Closed by gasman** 2015-08-23 19:29 UTC

**Comment by creativedutchmen** [comment] 2015-08-23 19:32
Apologies. Glad this is already on the radar.

Note to self: search for more than a minute before submitting.
