### ISSUE TITLE
Deactivate upload button while uploading

### ISSUE THREAD

**Issue by almeidarruben** [torchbox/wagtail#1062] opened 2015-03-16 16:40 UTC
During the upload, upload button should be deactivated. 

In my case, I was uploading to Amazon S3 and I pushed the button 2 times, it uploads the same image twice.

**Comment by davecranwell** [comment] 2015-03-16 17:37
Thanks for the feedback @almeidarruben. This is a duplicate of https://github.com/torchbox/wagtail/issues/305 and is currently being worked on.

**Closed by davecranwell** 2015-03-16 17:37 UTC
