### ISSUE TITLE
MyPage.objects.all() returns all pages, if custom Manager is specified for MyPage

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#2890] opened 2016-08-04 10:36 UTC
**Steps to reproduce:**

1. Checkout `wagtaildemo` (patch can be applied on top of https://github.com/torchbox/wagtaildemo/commit/e73170a1ac4eb30f1a071e81542b21c136ced1cd) and run with initial data.
2. Apply the patch
3. Run `./manage.py makemigrations && ./manage.py migrate`
4. Run `./manage.py shell`
5. Copy and paste the following snippet into the python interactive console:

    ```python
    from demo.models import EventPage
    EventPage.objects.all()
    ```

**Result:**
```python
>>> from demo.models import EventPage
>>> EventPage.objects.all()
[<Page: Root>, <Page: Home page>, <Page: Events index>, <Page: Event 1>, <Page: Event 2>, <Page: Blog index>, <Page: Blog post>, <Page: Blog post again>, <Page: Another blog post>, <Page: Standard index>, <Page: Standard page 1>, <Page: Standard page 2>, <Page: Photo credits>, <Page: A deeper menu level>, <Page: A grandchild page>, <Page: Another grandchild page>, <Page: People>, <Page: James Joyce>, <Page: David Mitchell>, <Page: Contact page>]
>>> type(EventPage.objects.first())
<class 'wagtail.wagtailcore.models.Page'>
```

**Expected result:**
```python
>>> from demo.models import EventPage
>>> EventPage.objects.all()
[<EventPage: Event 1>, <EventPage: Event 2>]
>>> type(EventPage.objects.first())
<class 'demo.models.EventPage'>
```

**Note**: `objects` manager works as expected, if there no any other managers.

**Versions:**

I can reproduce this issue with the following versions:

1. Wagtail==`master` + Django==1.10
2. wagtail==1.5.3 + Django==1.9.7

--
```diff
diff --git a/demo/models.py b/demo/models.py
index 897ac09..cd4d6b1 100644
--- a/demo/models.py
+++ b/demo/models.py
@@ -4,8 +4,9 @@ from django.db import models
 from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
 from django.http import HttpResponse
 from django import forms
+from django.utils import timezone

-from wagtail.wagtailcore.models import Page, Orderable
+from wagtail.wagtailcore.models import Page, Orderable, PageManager
 from wagtail.wagtailcore.fields import RichTextField, StreamField
 from wagtail.wagtailadmin.edit_handlers import FieldPanel, FieldRowPanel, MultiFieldPanel, \
     InlinePanel, PageChooserPanel, StreamFieldPanel
@@ -556,6 +557,16 @@ class EventPageSpeaker(Orderable, LinkFields):
     ]


+class FutureEventPageManager(PageManager):
+    def get_queryset(self):
+        queryset = super(self, FutureEventPageManager).get_queryset()
+        queryset = queryset.filter(
+            Q(time_from__gte=timezone.now()) | Q(time_to__gte=timezone.now())
+        )
+
+        return queryset
+
+
 class EventPage(Page):
     date_from = models.DateField("Start date")
     date_to = models.DateField(
@@ -579,6 +590,8 @@ class EventPage(Page):
         related_name='+'
     )

+    future_objects = FutureEventPageManager()
+
     search_fields = Page.search_fields + [
         index.SearchField('get_audience_display'),
         index.SearchField('location'),
```

**Comment by RadoRado** [comment] 2016-08-18 13:37
Hey man, why not use `objects` instead of `future_objects` when defining the manager? This seems to be the problem :panda_face:

**Comment by m1kola** [comment] 2016-08-18 13:44
HI @RadoRado!

Sometimes you need to have more than one managers. Like in description above:

* You need to have `objects` manager to be able to work with all `EventPage`s
* And you need to have `future_objects` to deal with `EventPage`s whose `time_from` or `time_to` in feature.

**Comment by gasman** [comment] 2016-08-18 19:09
@m1kola I haven't quite worked out why it's failing in this particular way yet, but did you really intend to override the _default_ manager here? Django will use the first manager defined on the model as the default one ([see docs](https://docs.djangoproject.com/en/1.10/topics/db/managers/#default-managers)). If you want to avoid that, you probably need to define the `objects` manager explicitly:

    class EventPage(Page):
        ...
        objects = PageManager()
        future_objects = FutureEventPageManager()

**Comment by m1kola** [comment] 2016-08-19 09:40
> did you really intend to override the default manager here? Django will use the first manager defined on the model as the default one (see docs).

No, I didn't know that Django does any magic with managers.

**Comment by gasman** [comment] 2016-08-19 12:00
I'll close this as invalid. I'm pretty sure that the behaviour seen here is caused (at least partially) by the fact that the default manager is being redefined - and that's something you'd usually want to avoid doing, so it's hard to say what the expected behaviour is here.

The actual behaviour does seem surprising, and I wouldn't rule out the possibility that there's a legitimate bug here affecting non-default managers (which we do support, as per http://docs.wagtail.io/en/v1.6/topics/pages.html#custom-page-managers) - or possibly the documentation is missing some key information about how to retain the expected "only return pages of this type" behaviour that the default manager implements. If so, I'd suggest raising that as a new ticket with a new test case.

**Closed by gasman** 2016-08-19 12:00 UTC
Labels: type:Bug
