### ISSUE TITLE
Link workflow in rich text editor. 

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1547] opened 2015-07-23 13:39 UTC
The current link workflow in the Wagtail rich text editor is frustrating. 

You can select a piece of text, add a hyperlink to that text but then if you want to edit the link (or even see where the link goes you can't. By clicking on the hyperlink icon with the link selected you remove the link. The obvious solution (that most CMS have) is to have a create and break link icon set. However I feel we can probably implement a more intelligent solution.

**Comment by tmsndrs** [comment] 2015-07-23 13:52
![wagtail_link_workflow 1](https://cloud.githubusercontent.com/assets/7290588/8851937/397163da-314a-11e5-9c5b-492219b15c96.gif)

**Comment by davecranwell** [comment] 2015-07-23 13:59
Duplicate of https://github.com/torchbox/wagtail/issues/444

**Closed by davecranwell** 2015-07-23 13:59 UTC
