### ISSUE TITLE
PageChooserPanel with foreign key linked to specific model: inconsistent behaviour

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#509] opened 2014-07-25 14:11 UTC
In the following example, `foo` is a page chooser field, where the developer has decided to limit the pages choosable to only those of a specific type rather than generic `wagtailcore.Page`. 

```
class MyPageThingy(Orderable):
    page = ParentalKey('core.MyPage', related_name='thingies')
    foo = models.ForeignKey('core.DifferentPage', related_name='+', null=True, blank=True,)
  
    panels = [
        PageChooserPanel('foo'),
    ]
```

I'd expect it to behave the same as the following:

```
class MyPageThingy(Orderable):
    page = ParentalKey('core.MyPage', related_name='thingies')
    foo = models.ForeignKey('wagtailcore.Page', related_name='+', null=True, blank=True,)
  
    panels = [
        PageChooserPanel('foo', 'core.DifferentPage'),
    ]
```

However while in the latter, the popup modal indicates that a restriction is in force, in the former no such indication is made and any page appears to be choosable.

In fact after selecting a "wrong" page then saving the changes, the user is given the comically poor message "Select a valid choice. That choice is not one of the available choices." 

Ideally the two versions above should behave the same, at least in terms of how the popup modal works.

**Comment by gasman** [comment] 2015-01-28 11:20
Hi @coredumperror - just to let you know I'm now working on a refactor of edit handlers so that they have access to the model class, as this is required by #823. This will allow us to solve this easily, and also to ditch the redundant `base_model` argument on `InlinePanel`.

**Comment by coredumperror** [comment] 2015-01-28 18:27
Glad to hear it!

**Comment by zerolab** [comment] 2015-02-10 22:08
I have tested with latest master and the PageChooserPanel behaves correctly as expected in the first example. However, it seems that the changes break the page chooser -- it now displays as dropdown rather that the usual "Choose a page" button and modal. c542494 is a working commit. Consequent commits show the button (does nothing) and the dropdown. Latest master does away with the button alltogether.

Worth moving to a separate issue as the gist of this one has been fixed with #960.

Will look more into this tomorrow.

**Comment by gasman** [comment] 2015-02-17 16:10
@zerolab Is this still failing for you on master? I've just tried various permutations of PageChooserPanel on wagtaildemo, and they're all rendering as expected (bearing in mind that the change proposed in this ticket has not yet been implemented):

* `PageChooserPanel('link_page')` where `link_page` is a foreign key to `wagtailcore.Page` (shows the chooser and allows choosing any page)
* `PageChooserPanel('link_page', 'demo.eventpage')` where `link_page` is still a foreign key to `wagtailcore.Page` (shows a chooser that only allows selecting pages of type "Event Page")
* `PageChooserPanel('link_page', 'demo.EventPage')` where `link_page` is still a foreign key to `wagtailcore.Page` (just in case capitalisation is significant - same as above)
* `PageChooserPanel('link_page')` where `link_page` is a foreign key to `demo.EventPage` (shows the chooser and allows choosing any page, aka the current broken behaviour)

**Comment by zerolab** [comment] 2015-02-19 14:26
@gasman just saw the notification on this. With the master from yesterday, I also get the expected behavior, as reported initially.

However I still only get a dropdown rather than the actual page choose modal. I suspect this may be a red herring, will try with a fresh install later.

**Closed** 2015-02-20 10:49 UTC
Labels: Bug

**Comment by davecranwell** [comment] 2015-02-20 11:34
Is there a documentation update needed here? I'm now slightly unclear which of the two examples in the opening comments are correct/best.

**Comment by gasman** [comment] 2015-02-20 11:58
The latter version is better, because if 'foo' is meant to point to an instance of core.DifferentPage specifically, it's better for that to be defined at the model/database level rather than just in the user interface. It's an extra level of validation to ensure that non-DifferentPage objects don't creep in, and it ensures that if you access `my_page_thingy.foo` in a template, you'll get an instance of core.DifferentPage back and not have to call `specific` on it.

There's no immediate urgency to migrate existing working code to the new scheme, though.
