### ISSUE TITLE
Cannot overwrite image attributes in template with empty values

### ISSUE THREAD

**Issue by crafft** [torchbox/wagtail#1933] opened 2015-11-18 12:58 UTC
For certain images in my templates I want to set an empty alt attribute.

[According to the documentation](http://docs.wagtail.io/en/v1.2/topics/images/using_in_templates.html#image-tag-alt) this is done with

    {% image obj.image alt="" %}

But this does not work, and I think it should.

If I overwrite an attribute this way, wagtail should not make any checks of my values and just accept them.

**Comment by nealtodd** [comment] 2015-11-18 13:23
This might be related to use of a mutable dict default for the attrs kwarg of ImageNode: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/templatetags/wagtailimages_tags.py#L34

This should probably be None with a check in the init to set it to an empty dict if a dict isn't passed in.

**Comment by gasman** [comment] 2015-11-18 13:34
The problem is in the implementation of `Rendition.img_tag` https://github.com/torchbox/wagtail/blob/0f0310858b015a62fcaf342108b76ea038b5bd45/wagtail/wagtailimages/models.py#L448 - it's only designed to support passing in extra attributes, not replacing the default ones (and the documentation is consistent with this). The ability to override the default attributes would be a reasonable thing to add, though.

(@nealtodd, the use of `attrs={}` in the tag is harmless, because that property never gets altered anywhere in the `ImageNode` implementation. I admit it did make me go 'eww' on first glance though :-) )

**Comment by nealtodd** [comment] 2015-11-18 13:35
Actually, that might not be the cause (but should be addressed anyway, and I think there are some other uses of mutable defaults elsewhere. PR coming up for those).

I may be tracing the through the code path wrongly but it looks like any attributes matching the image's own ones don't replace them, they get added as well, with the images own ones coming first (and the browser parsing meaning it wins out):
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/models.py#L451

**Comment by nealtodd** [comment] 2015-11-18 13:35
Snap! :)

**Comment by andycrafft** [comment] 2015-11-18 14:53
In Chrome Dev Tools one would not see the duplicate attributes – so I checked with wget, and actually the overwritten attribute appears twice in HTML.

Chrome is apparently always taking the first attribute, if it's set several times in HTML, no matter if the latter are empty or have a value!

Hence overwriting attributes should not work at all (at least in Chrome?), and this should be fixed.

**Comment by timheap** [comment] 2015-11-19 00:21
Django contains a very useful and very poorly documented utility called [`flatatt`](https://github.com/django/django/blob/1.8.6/django/forms/utils.py#L21) that is useful in this case, which I've used to solve this issue in #1938

**Closed** 2015-11-24 11:38 UTC
Labels: Ready to develop!
