### ISSUE TITLE
MultiValueDictKeyError: "'body-0-deleted'"

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#1697] opened 2015-09-17 07:51 UTC
We keep getting this issue:

```bash
MultiValueDictKeyError: "'body-0-deleted'"
  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/cache.py", line 38, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "wagtail/wagtailadmin/views/pages.py", line 150, in create
    validate_page_form(form, parent_page)
  File "wagtail/wagtailadmin/views/pages.py", line 311, in validate_page_form
    form.full_clean()
  File "django/forms/forms.py", line 353, in full_clean
    self._clean_fields()
  File "django/forms/forms.py", line 362, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "wagtail/wagtailcore/blocks/base.py", line 457, in value_from_datadict
    return self.block_def.value_from_datadict(data, files, name)
  File "wagtail/wagtailcore/blocks/stream_block.py", line 138, in value_from_datadict
    if data['%s-%d-deleted' % (prefix, i)]:
  File "django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
```

Here is the body:

```python
{
action-submit: Submit for moderation, 
author: The Late Show, 
body-count: 1, 
cover_image: 21679, 
csrfmiddlewaretoken: 5h4B0Z7TacaIIPPQDs1LyNuJlJp3o3Iq, 
expire_at: , 
go_live_at: , 
page_relations-INITIAL_FORMS: 0, 
page_relations-MAX_NUM_FORMS: 1000, 
page_relations-MIN_NUM_FORMS: 0, 
page_relations-TOTAL_FORMS: 0, 
search_description: , 
seo_title: , 
slug: dislike-or-not-dislike, 
summary: <p>The rumors are true, Facebook is creating a "Dislike" button.</p>, 
tags: Kriya,Gangiah,FrankieDuToit,TheLateShow,facebook,dislike, 
title: To "Dislike" or not to "Dislike"
}
```

It seems to be related to this:

http://stackoverflow.com/questions/5895588/django-multivaluedictkeyerror-error-how-do-i-deal-with-it

**Comment by gasman** [comment] 2015-09-17 11:05
Presumably the `body` field is a StreamField here? This is failing because `body-count` shows that there is a single item in the StreamField, but none of the expected form fields for that item are in the form submission. (I would expect to see, at minimum, `body-0-deleted`, `body-0-order` and `body-0-type`.) When this error occurs, have you added any content to the `body` field, or left it blank? Do you get any errors in your browser's Javascript console? (The warning `'Range.detach' is now a no-op, as per DOM` can be ignored)

**Comment by lee-kagiso** [comment] 2015-09-17 12:27
It is a Streamfield yes.

This comes from Sentry via an enduser.

Here are the Sentry reports:
https://beta.getsentry.com/share/group/34313638322e3735353038313637/
https://beta.getsentry.com/share/group/34313638322e3739333834373339/

**Comment by gasman** [comment] 2015-09-17 14:57
OK - I think this is caused by the editor using the 'back' button while editing. I've been able to reproduce it with the following steps:

* create a new page with a streamfield
* Add a block to the streamfield
* Navigate away from the page (e.g. by clicking 'Images' in the menu)
* Use the browser's back button
* Submit the form

I don't think it's possible to eliminate this entirely - the browser is trying to restore the previous state of the form (including the hidden field that specifies how many blocks there are in the streamfield), but fails because the form HTML changes dynamically during editing. However, this will be mitigated by #475, which discourages users from casually browsing away from the page editor - therefore I'll close this as a duplicate of #475.

**Closed by gasman** 2015-09-17 14:57 UTC
Labels: Needs info

**Comment by 2dor** [comment] 2017-04-05 07:22
Hi, I'm getting the same error when I'm saving a draft.

I have the following blog page class:
```python
class BlogPage(Page):
    main_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    date = models.DateField("Post date")
    intro = models.CharField(max_length=250)
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('paragraph', blocks.TextBlock()),
        ('image', ImageChooserBlock()),
    ])

    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('date'),
        ImageChooserPanel('main_image'),
        FieldPanel('intro'),
        FieldPanel('body'),
    ]
```
When I click on the plus button to add a new block to the body section, it just doesn't do anything. In the console I get the following messages:
```javascript
rangy-core.js:80 The behavior that Selection.addRange() merges existing Range and the specified Range is deprecated and will be removed in M58, around April 2017. See https://www.chromestatus.com/features/6680566019653632 for more details.
(anonymous) @ rangy-core.js:80
(anonymous) @ rangy-core.js:80
(anonymous) @ rangy-core.js:15
N @ rangy-core.js:11
q @ rangy-core.js:16
stream.js:87 Uncaught TypeError: Cannot read property 'initializer' of undefined
    at Object.onInitializeMember (stream.js:87)
    at postInsertMember (sequence.js:95)
    at Object.self.insertMemberAfter (sequence.js:166)
    at Object.self.appendMember (sequence.js:32)
    at Object.onChooseBlock (stream.js:112)
    at HTMLButtonElement.<anonymous> (stream.js:60)
    at HTMLButtonElement.dispatch (jquery-2.2.1.js:4732)
    at HTMLButtonElement.elemData.handle (jquery-2.2.1.js:4544)
onInitializeMember @ stream.js:87
postInsertMember @ sequence.js:95
self.insertMemberAfter @ sequence.js:166
self.appendMember @ sequence.js:32
onChooseBlock @ stream.js:112
(anonymous) @ stream.js:60
dispatch @ jquery-2.2.1.js:4732
elemData.handle @ jquery-2.2.1.js:4544
```
If I try to save the draft, I get the following error and a stack trace similar to the one above. 
```python
MultiValueDictKeyError at /admin/pages/add/blog/blogpage/1/
"'body-0-deleted'"
```

**Comment by gasman** [comment] 2017-04-05 08:21
> EDIT: The error below is caused by the fact that the 'body' content panel is referenced as a FieldPanel, instead of a StreamFieldPanel. How can one prevent such mistakes?

Eliminating StreamFieldPanel as a separate panel type is discussed here: #1939

**Comment by lud2k** [comment] 2017-04-19 20:31
I am experiencing the same issue as @gasman on Sep 17, 2015. I've reproduced it the same way on Wagtail 1.8. Is there a way to fix this?

**Comment by gasman** [comment] 2017-04-20 00:06
@lud2k As I said in my comment, I can't see a feasible way to fix it - it's not really a Wagtail bug, as it's triggered by the browser trying to be clever and restoring the form contents when using the back button, but failing to make the corresponding changes to the form structure. Now that we have the 'unsaved changes' warning, it should be harder to trigger this by accident - for that reason, we have no further plans to fix this. However, we'd definitely welcome pull requests from the wider community aimed at addressing this.

**Comment by pySilver** [comment] 2020-10-22 12:36
@gasman for some reason it also happening when one authorized user shares preview link with another.

**Comment by gasman** [comment] 2020-10-22 12:42
@pySilver Please open a new issue with the full details - anything involving users sharing URLs sounds like a different issue, since there clearly can't be any POST data in that situation.

**Comment by pySilver** [comment] 2020-10-22 12:47
@gasman sure, I will once I catch the root of it. Its kinda strange.. when sharing preview link with my own account (different browsers, incognito when the same) I'm getting expected screen saying `Impossible to preview this page, some errors are remaining. Please close this tab, edit the page to fix these errors, then use preview again.` but when shared with another authenticated user - he instantly gets exception :)

**Comment by pySilver** [comment] 2020-10-22 12:56
@gasman ok I think I have a good theory. This exception happens to users that were editing this particlar page before in Chrome browser. If they open preview URL in chrome - exception occurs, if they open it any other browser – expected warning screen shows up. My guess its Chrome tries to restore form state in this case too. Thing is – if we can somhow detect outdated post request ato show warning screen.

**Comment by tomkins** [comment] 2021-08-03 19:16
We've recently had this occur when sharing preview links, hopefully recreatable with #7392.
