### ISSUE TITLE
Required fields in streamfield are not given an asterisk

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#2237] opened 2016-02-15 12:57 UTC
Minor UI issue.

If I add ``required=True`` to a field in a ``StructBlock``. The fact the field is required is not indicated in the UI with a red asterisk, like database fields are.

**Comment by alexgleason** [comment] 2016-02-15 14:07
Duplicate of #1732

**Closed by alexgleason** 2016-02-15 14:07 UTC
Labels: Bug, Streamfield
