### ISSUE TITLE
Do not allow delete on pages with children or at least show warning

### ISSUE THREAD

**Issue by chhantyal** [torchbox/wagtail#1667] opened 2015-09-08 15:59 UTC
I had a page with hundreds of child pages. Looks like someone accidentally deleted said parent page, and all data is gone. I have backup, but lots of things have changed on current data and backup from yesterday is not going to adjust/fix this properly.  

This is not very nice thing to happen, few things we could do.
1. Show list of child pages that are going to be deleted because of parent page removal (this is similar to how django shows list of related objects that are going to be deleted when you delete an object)
2. Show warning that this is parent page and user might lose data (child pages)
3. Do not allow delete on parent page. First delete child pages, and once the parent page itself is leaf node, it can be deleted. Otherwise not.

Last thing, [Edit: There is separate issue #496] it would be nice to have something similar to django admin log. It keeps simple logs of all the actions performed  via admin.

**Comment by davecranwell** [comment] 2015-09-08 16:08
Sorry to hear of that unfortunate accident. I believe this is a duplicate of #687 and #496

**Comment by chhantyal** [comment] 2015-09-08 16:10
Sorry but I don't think it is duplicate of #687 That one talks about related objects, above issue is about child pages.

**Comment by gasman** [comment] 2015-09-08 16:11
Agreed...

**Comment by davecranwell** [comment] 2015-09-08 16:13
hmm, you're right. #496 covers the logging, but I'm sure there's another ticket somewhere that mentioned listing the affected objects of a proposed deletion.

**Comment by davecranwell** [comment] 2015-09-08 16:19
I think a combination of 1. and 2. would work best. Suggestion 3. is likely to prove problematic, since deleting a top-level section should be possible and if it contained hundreds of subsections, each with their own pages, they too would be undeletable till their children were deleted. Even with Bulk Actions (#121) I think that would be a pain.

**Comment by coredumperror** [comment] 2016-03-09 01:17
I don't think simply warning users is going to be enough here, because too many users have deletion permission in the first place due to #596. Even with a warning, a user who isn't paying attention (and don't say you've never clicked OK without reading the warning message. We've all done that.) can still accidentally delete hundreds of pages they don't own unless you outright deny deletion of Pages that have children.

But if that's too draconian, maybe you could add a special permission for the "delete this page and all of its children" action. That way the catastrophic accidents are at least restricted to a small cadre of privileged Administrators, rather than a potentially massive swarm of editors.

**Comment by davecranwell** [comment] 2016-03-09 09:25
Relevant: https://github.com/torchbox/wagtail/issues/2213

I think @alexgleason sold us on the idea of "Undo" functionality which would make any change non-destructive and in turn would make deleting pages with children far less of a concern to administrators. We've not begun to look into undo yet, but it should be considered here.

**Comment by bbusenius** [comment] 2016-04-22 14:42
This issue is already biting us on our recently launched site. Internally we talked about all the ideas mentioned here. The "undo" functionality is by far our favorite solution, however, other incremental changes to the UI would be better than nothing. As it stands, it's far too easy for users to unwittingly do massive damage. On large sites, with multiple authors, restoring the database to a previous version doesn't work for the reason that @chhantyal mentioned.

**Comment by gasman** [comment] 2016-09-29 09:18
Have now created https://github.com/torchbox/wagtail/pull/3035 to address this - I've adopted of @coredumperror's suggestion of making bulk deletion (i.e. the ability to delete a page with children) a separate permission type. In the default setup (and the one that I expect the vast majority of sites to keep), no 'ordinary' users are given this permission, meaning that it's available only to superusers. Feedback welcomed...

**Comment by gasman** [comment] 2016-11-03 17:07
Fixed in #3035.

**Closed by gasman** 2016-11-03 17:07 UTC
Labels: status:Design decision needed, type:Enhancement
