### ISSUE TITLE
Non-page models with tags have to be saved twice

### ISSUE THREAD

**Issue by alexpilot11** [torchbox/wagtail#2161] opened 2016-01-27 17:58 UTC
Models that are not pages with tags have to be saved twice. I believe there was a workaround for pages put in place, but other models with tags still have the same issue. Original issue: https://github.com/torchbox/wagtail/issues/197

**Comment by gasman** [comment] 2016-01-27 18:24
Hi @alexpilot11,
What sort of models - snippets, images/documents, or something else?

**Comment by alexpilot11** [comment] 2016-01-27 18:31
We created a Video model that is similar to images

**Comment by gasman** [comment] 2016-01-28 00:13
Does the bug happen for images too? If so, please can you provide a set of steps for reproducing this within the image admin area?

If it's only happening on an admin module you've created yourself (either based on wagtailimages, or otherwise) then we'll need more information to confirm that this is indeed a Wagtail bug, rather than a bug in your code or a third-party module - as it stands, all we know for sure is that your code is showing a bug *similar* to one that used to exist in Wagtail. (Indeed, there's probably not much Wagtail-specific code there: most likely, it's using standard Django views/forms along with django-taggit and the jQuery Tag-It library.) If you can isolate the problem, and show that there's a specific Wagtail API that's not behaving as intended, then we can investigate further.

**Comment by alexpilot11** [comment] 2016-01-28 21:01
It doesn't seem to happen on images from what I can see. If I do isolate the error I will let you know.

Thanks

**Comment by gasman** [comment] 2016-02-02 17:34
Will close this for now - please reopen if you can provide the necessary info. Cheers!

**Comment by chrxr** [comment] 2016-02-19 19:42
Hi @gasman,

reopening this ticket as I think I have the same issue. Created a snippet with tags, and the tags do not persist on save. Checked the DB, and tables are empty. This is my model:

    class BookmarkTag(TaggedItemBase):
        content_object = ParentalKey('blog.Bookmark', related_name='tagged_items')

    class Bookmark(ClusterableModel):
        url = models.URLField("Bookmark URL")
        title = models.CharField("Bookmark title", max_length=255, blank=True)
        notes = RichTextField("Bookmark notes", null=True, blank=True)
        date_read = models.DateField()
        tags = ClusterTaggableManager(through=BookmarkTag, blank=True)

        panels = [
            FieldPanel('url'),
            FieldPanel('title'),
            FieldPanel('notes'),
            FieldPanel('date_read'),
            FieldPanel('tags'),
        ]

        def __str__(self):
            return self.title

    register_snippet(Bookmark)

**Comment by chrxr** [comment] 2016-02-20 11:31
Looks like this is actually my error. Should be using:

    tags = TaggableManager(through=BookmarkTag, blank=True)

rather than ClusterTaggableManager

Sorry about that.

**Closed** 2016-02-20 11:36 UTC
Labels: Needs info
