### ISSUE TITLE
File upload: Filefield in wagtail admin doesn't work with FieldPanel

### ISSUE THREAD

**Issue by chhantyal** [torchbox/wagtail#1329] opened 2015-05-21 13:50 UTC
In many cases, file upload can be managed with wagtaildocs app, but there are use cases where you just want to upload files in FileField. This doesn't work with wagtail admin cause we don't specify `enctype=multipart/form-data` during form submission [see screenshot]. 

Django seems to handle this with `has_file_field` template var https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/change_form.html#L40, but this is bit lame as that boolean is always true https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/change_form.html#L40

If this solution is fine, let me know. Happy to send PR :)

![screen shot 2015-05-21 at 15 47 56](https://cloud.githubusercontent.com/assets/862941/7749884/eda218e6-ffd0-11e4-8708-c80cd2ba93ee.png)

**Comment by gasman** [comment] 2015-10-16 11:15
Fixed in #1741

**Closed by gasman** 2015-10-16 11:15 UTC
Labels: Enhancement

**Comment by miscellainiac** [comment] 2015-12-11 17:22
I'm not sure that this is working as intended. I have a FileField on a model, but it has to be a Page (it can't be any arbitrary model that is related to a Page later). Running locally, the upload appears to work, but nothing is saved to my MEDIA.

Using the django-admin, instead of the wagtail admin uploads the file correctly.

Django==1.8.7
wagtail==1.2
