### ISSUE TITLE
Image feature detection fails on 1.0b1 with "I/O operation on closed file"

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1256] opened 2015-05-01 09:45 UTC
As reported here: https://groups.google.com/d/msg/wagtail/5zSvx5g_vhM/LlrxA9Y73ncJ

**Comment by kaedroho** [comment] 2015-05-01 09:55
I'll also see if I can add a test or two for feature detection to hopefully catch these sort of problems in the future

**Comment by kaedroho** [comment] 2015-05-06 12:27
This was caused by ``get_willow_image`` (used by feature detection) closing the file after the feature detection was done, causing an error to be raised when Django tried to save it.

Fix: https://github.com/torchbox/wagtail/pull/1273

**Closed** 2015-05-13 09:02 UTC
Labels: Bug, Images, Release blocker
