### ISSUE TITLE
Image upload system does not catch errors caused by exceeding webserver maximum filesize/POST-size

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#616] opened 2014-09-10 09:13 UTC
We've experienced these errors one of our staging servers when the user tried to upload a 4MB image.

`2014/09/10 09:46:33 [error] 27068#0: *86706 client intended to send too large body: 4405744 bytes, client: ...`

The result of which is the image upload system falling back to its most default error message, "An error occurred". This needs addressing to improve this useless message and to avoid us repeatedly troubleshooting this for other people. 

Wagtail's image features are all about high quality images so it seems likely that user would be eager to have large original image files and would therefore encounter file size limits, whatever they are, regularly.

Ideally wagtail would somehow be made aware of the server's filesize/post limits. Failing that, the implementer would define a settings entry relating to filesize which merely duplicated the underlying server's limits. Perhaps by setting this low enough and commenting suitably, implementers would be more likely to remember to raise the limit.

**Comment by gasman** [comment] 2016-02-05 16:28
Reporting server errors back to the user is now implemented for the image/document chooser modals in #2167 - just the primary `/images/` / `/documents/` upload views to sort now.

**Comment by nfletton** [comment] 2016-02-05 17:17
@gasman I'll take a look. For some reason I thought I'd tested that and the response seemed acceptable but perhaps I imagined it.

**Comment by gasman** [comment] 2016-02-05 17:18
@nfletton Thanks! When I tried just now, I got a basic 'Upload error' message without the specific error code / message.

**Comment by nfletton** [comment] 2016-02-17 23:25
@gasman The /images/ upload now handles this error in #2209. This issue cannot be easily addressed for /documents/ as it uses standard model forms (no AJAX) and therefore the error cannot be intercepted in the browser. I don't think it's worthwhile addressing that. #2250 addresses any OS errors that may occur with document uploads though.

**Comment by gasman** [comment] 2016-04-25 22:51
Fixed in #2209.

**Closed by gasman** 2016-04-25 22:51 UTC
Labels: Enhancement, Images, Ready to develop!

**Comment by prokaktus** [comment] 2017-12-23 21:18
I have feeling, that this logic become broken somehow. Because now when I stucked with this problem (my Nginx was configured with max size of 1mb), nothing was shown to me.

No errors were reported by Image Uploader:
![No errors were reported by Image Uploader](https://user-images.githubusercontent.com/193254/34322703-d7596706-e83f-11e7-95fd-e6c5fdcfcb83.png)

**Comment by gasman** [comment] 2018-01-03 00:03
@prokaktus Thanks for the report! I can confirm that the error report no longer appears on recent Wagtail versions - it seems that this was inadvertently dropped in #2538. Have now opened #4163 to fix this.
