### ISSUE TITLE
Allow custom document model

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2034] opened 2015-12-14 21:52 UTC
Wagtailimages has [custom image models](http://docs.wagtail.io/en/v1.2/topics/images/advanced_topics.html#custom-image-model). It would be very useful to have the same functionality for documents.

**Comment by kaedroho** [comment] 2015-12-15 12:33
Thanks @alexgleason! This appears to be a duplicate of #961 so I'll close this one

**Closed by kaedroho** 2015-12-15 12:33 UTC
