### ISSUE TITLE
Ability to edit links in rich text editor required

### ISSUE THREAD

**Issue by chrxr** [torchbox/wagtail#1246] opened 2015-04-29 09:01 UTC
All my clients so far have asked if it is possible to edit links in the rich text editor after creating them. I have had to say no, remove the link then recreate.

This is a bad user experience in itself, but it is exacerbated when migrating content from a previous website.

In a most recent clients build, we have found many relative URLs in migrated content which are resulting in 404s. In this situation we can change programatically, but it would be difficult for a user to fix these issues themselves.

Perhaps this ties in to discussions about alternatives to Hallo.js

**Comment by MechanisM** [comment] 2015-04-29 09:16
If talking about alternatives, I prefer smth like http://summernote.org/ - it has nice 'Air-mode' and also doesn't require fat jquery-ui.

**Comment by MechanisM** [comment] 2015-04-29 09:18
Currently, when clicking on richtext filed in admin area while you activating hallo, with this click you suddenly clicking on editor buttons and can change some formatting by mistake. you just clicked on textarea to edit it, but suddenly you also clicked on button of halo editor.

**Comment by BertrandBordage** [comment] 2016-03-17 17:03
Duplicate of #444.

**Comment by zerolab** [comment] 2016-03-17 21:27
Closing as duplicate. Let's continue discussion on #444.

**Closed by zerolab** 2016-03-17 21:27 UTC
Labels: Enhancement
