### ISSUE TITLE
No easy way to relate a page to multiple pages

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1767] opened 2015-10-02 19:29 UTC
Might be related to #231.

Preferably I'd be able to use a PageChooserPanel on a ManyToMany field, but that causes a runtime error.

I think a way around this could be to use a ListBlock containing PageChooserBlocks, but that's not exactly elegant. Similar to #1717 (see the screenshots on this one).

**Comment by gasman** [comment] 2015-10-04 12:08
The standard workaround for this is detailed in https://github.com/torchbox/wagtail/issues/231#issuecomment-42259691 - not ideal, I know...

Closing as duplicate of #231

**Closed by gasman** 2015-10-04 12:08 UTC

**Comment by kaedroho** [comment] 2015-10-04 15:15
Lack of M2M support should be mentioned in the docs somewhere

**Comment by alexgleason** [comment] 2015-10-05 16:36
@kaedroho Not sure what you mean and maybe I should have been more clear, but M2M does seem to "work". I haven't templated it yet, but I get this in the admin:

![screenshot from 2015-10-05 11 33 59](https://cloud.githubusercontent.com/assets/3639540/10286790/15a56ee8-6b55-11e5-842d-ff5d7681fedf.png)

It's just not an easy to use UI and I don't think it would scale well to thousands of entries.

The field:
```python
related_content = models.ManyToManyField('wagtailcore.Page', related_name='+', blank=True)
```

The panel:
```python
FieldPanel('related_content')
```

**Comment by alexgleason** [comment] 2015-10-07 20:58
Can anyone clarify this please?

**Comment by gasman** [comment] 2015-10-08 11:15
M2M relations are not currently supported because the relevant logic has not yet been implemented in django-modelcluster. (This is the library Wagtail uses internally to deal with object relations that don't correspond to the live database state - e.g. previewing and working with draft versions of pages). You may well find that they work to some extent (e.g. rendering the edit form) simply because those operations don't rely on django-modelcluster, but it will certainly fall over elsewhere - such as previewing the page, or editing a draft version of a page that has an existing published version.

**Comment by alexgleason** [comment] 2015-10-08 13:28
Thank you for the info!

**Comment by moreplavec** [comment] 2019-03-06 20:13
Is the "solution" related_content = models.ManyToManyField('wagtailcore.Page', related_name='+', blank=True) applicable or usable? Or is there already wagtail-way to achieve this?

**Comment by gasman** [comment] 2019-03-07 10:45
@moreplavec It would need to be `ParentalManyToManyField` - see https://docs.wagtail.io/en/stable/getting_started/tutorial.html#categories for an example. However, a M2M field to `wagtailcore.Page` will probably provide a pretty bad user experience, since it'll give you a list of checkboxes for all pages on the site - the old method (a page chooser inside an InlinePanel) would almost certainly work better.

**Comment by moreplavec** [comment] 2019-09-14 18:13
Is there something new about linking more pages from another one? Now I need to link product pages and found this old thread still open as the one and only. I will try ParentalManyToManyField, but something more user-friendly would be nice.
