### ISSUE TITLE
Cannot save tags from inline panel

### ISSUE THREAD

**Issue by stefangeorg** [torchbox/wagtail#2855] opened 2016-07-19 14:53 UTC
I have the following models:

```python
class NewsPage(BasePage):
    template = 'pages/news.html'

    panels = Page.content_panels + [
        FieldPanel('section_title'),
        FieldPanel('description'),
        FieldPanel('teaser'),
        InlinePanel('news_items', label='News Items')
    ]

    edit_handler = TabbedInterface([
        ObjectList(panels, heading='Content'),
        ObjectList(Page.promote_panels, heading='Promote'),
    ])


class NewsItemTag(TaggedItemBase):
    content_object = ParentalKey('pages.NewsItem', related_name='tagged_items')


class NewsItem(Orderable, ClusterableModel):
    page = ParentalKey(NewsPage, related_name='news_items', on_delete=models.PROTECT)
    title = models.CharField(max_length=255)
    link = models.URLField(blank=True)
    date_to_show = models.DateField(default=datetime.datetime.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    tags = TaggableManager(through=NewsItemTag, blank=True)

    panels = [
        FieldPanel('title'),
        FieldPanel('link'),
        FieldPanel('date_to_show'),
        ImageChooserPanel('image'),
        FieldPanel('tags')
```

However any time I save it, the new tags are not saved. If I add one via the shell

   a.tags.add("business")

Then it saves, and shows in the admin, and doesn't get erased, but cannot add any other tags on save.

Here are the posted values:

```
news_items-0-tags:business
news_items-0-id:1
news_items-0-ORDER:1
news_items-0-DELETE:
news_items-1-title:Hidden Inside Amazon  BY ALEX FRITZPATRICK | TIME  Business Entertainment 26-04-2016   California Gov. Jerry Brown Backs Hillary Clinton in Call for an End to Democratic Fight 10:21 AM ET
news_items-1-link:http://www.yahoo.com
news_items-1-date_to_show:2016-07-19
news_items-1-image:5
news_items-1-tags:business,news
```

So they are being submitted, but it doesn't seem like there is anything I can do to get them to save without editing some wagtail backend code.

**Comment by gasman** [comment] 2016-07-19 14:57
Duplicate of #1221

**Closed by gasman** 2016-07-19 14:57 UTC
