### ISSUE TITLE
Wagtail API show incorrect detail_url

### ISSUE THREAD

**Issue by mevinbabuc** [torchbox/wagtail#2991] opened 2016-09-12 07:31 UTC
Wagtail Images API show  incorrect `detail_url` when the Wagtail API is registered with a different URL than suggested in the documentation.

**How to reproduce**
Register Wagtail API on a different URL than suggested in the documentation. In my case it was registered under
`url(r'^unchained/cms/wagtail-api/', include(wagtailapi_urls)),`

Go to the defined URL `http://127.0.0.1:8000/unchained/cms/wagtail-api/v1/images/`

The detail URL field shows  `"detail_url": "http://localhost/cms/api/v1/images/1/"` which results in a `404`. 

The expected outcome should be `"detail_url": "http://localhost/unchained/cms/wagtail-api/v1/images/1/"`

Wagtail version: 1.6.2
Python: 3.4

**Comment by mevinbabuc** [comment] 2016-09-12 08:00
I just noticed that its the same behavior with the Pages API too.

**Comment by jjanssen** [comment] 2016-09-13 18:42
I am not sure if this a bug, since I am not able to reproduce it myself. 

What I do know is that Wagtail looks into the `wagtail.wagtailsites` configuration in order to compose the absolute URL. Can you validate if your development settings are configured at `localhost` and port `8000` within Settings > Sites?

![image](https://cloud.githubusercontent.com/assets/287422/18486645/272ca63e-79f2-11e6-8618-58920622b350.png)

**Comment by jjanssen** [comment] 2016-09-13 18:48
Sorry, for the unrelevant answer that maybe showed up in the mailbox. Overlooked your complete example. So yeah, can confirm :)

**Comment by laidibug** [comment] 2016-10-15 23:08
Here is what I did to try to replicate your issue:
I changed api url to
```url(r'^unchained/cms/wagtail-api/', include(wagtailapi_urls)),```

I went to
http://127.0.0.1:8000/unchained/cms/wagtail-api/v1/images/

This is one of the entries:
```
{
    "id": 4,
    "meta": {
        "type": "wagtailimages.Image",
        "detail_url": "http://localhost/unchained/cms/wagtail-api/v1/images/4/"
    },
    "title": "Wagtail by Mark Harkin"
}
```

I went to http://127.0.0.1:8000/unchained/cms/wagtail-api/v1/pages/
I can see:
```
 {
    "id": 2,
    "meta": {
        "type": "demo.HomePage",
        "detail_url": "http://localhost/unchained/cms/wagtail-api/v1/pages/2/"
    },
    "title": "Home page"
}
```

The detail_url is correct on both cases.
Are you able to test your issue against the latest release?

**Comment by gasman** [comment] 2016-10-25 10:41
Closing as unable to replicate. If you can confirm that this issue still occurs on the current release, please provide steps for reproducing the bug and we'll investigate further.

Thanks for the investigation @laidibug!

**Closed by gasman** 2016-10-25 10:41 UTC
Labels: component:API, status:Needs info, type:Bug
