### ISSUE TITLE
AbstractEmailForm serve() does not use get_context()

### ISSUE THREAD

**Issue by pa-jama** [torchbox/wagtail#1545] opened 2015-07-23 03:19 UTC
Its quite undesirable to add extra context into a form page, as the default serve() does not call get_context(). It is surprising since normally pages serve use get_context, which can be overridden to add extra context.

To add extra context currently, would have to copy paste the source of serve, just to add some context.

**Comment by kaedroho** [comment] 2015-07-23 09:02
Thanks @pa-jama 

This should be fixed in: https://github.com/torchbox/wagtail/pull/1541 (reviews welcome!)

**Comment by gasman** [comment] 2015-07-23 16:14
Closing as duplicate of #1429/#1541.

**Closed by gasman** 2015-07-23 16:14 UTC
Labels: Enhancement
