### ISSUE TITLE
Adding image tag doesn't save

### ISSUE THREAD

**Issue by jossingram** [torchbox/wagtail#629] opened 2014-09-12 15:01 UTC
Just trying 0.6 on our existing site locally, and when you upload an image, then specify a tag then click update, it doesn't save it to the database.

if you go back to the main images folder then select the image, then tag it, that works fine.

**Comment by mope** [comment] 2015-01-06 11:05
Hi Joss,

I've tried this on 0.8 and can't reproduce it. This is what I'm doing:

1. Navigate to http://[whatever]/admin/images/
2. Click 'Add An Image'
3. Click 'Or choose and image from your computer'
4. Choose an image and upload it
5. Enter a title and some tags, then click 'Update'.
6. Navigate back to http://[whatever]/admin/images/ and check the newly-created image

Am I using the correct steps?

**Comment by jossingram** [comment] 2015-01-06 15:03
I just tried it in 0.8.3 and it seems fixed now.

**Comment by gasman** [comment] 2015-01-06 15:15
Closing as resolved.

**Closed by gasman** 2015-01-06 15:15 UTC
Labels: Bug
