### ISSUE TITLE
Video embed causes massive padding bottom

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1801] opened 2015-10-07 20:44 UTC
![screenshot from 2015-10-07 15 38 31](https://cloud.githubusercontent.com/assets/3639540/10350419/89f2eec8-6d09-11e5-92be-8595f381373b.png)

It's happening because of this. https://github.com/torchbox/wagtail/blob/6479eb80ef2653ad52fa920b96ac7c5d6e35200a/wagtail/wagtailembeds/format.py#L14

Why is that padding being applied? The result for this video is 56.25% padding, or 358px. Also: this could be worked around more easily if the markup were given relevant classes to target this by. Right now it just has `responsive-object` but I'm not sure what else that could be used for so I'm hesitant to target it. It would be nice to have a class like `embed-video` on it.

**Comment by gasman** [comment] 2015-10-07 20:47
Duplicate of #1495

**Closed by gasman** 2015-10-07 20:47 UTC
