### ISSUE TITLE
Snippet chooser UI improvements

### ISSUE THREAD

**Issue by jimmymorrisuk** [torchbox/wagtail#666] opened 2014-10-03 11:21 UTC
There are a few parts to this so I will break them down. 

1) There's no title text on the snippet reference buttons. Although I know what the trash icon is meant to mean the up and down buttons, to some users, will be ambiguous, I had to click them to be sure. I recommend adding title text to all icon only buttons. 
It could also be argued that the trash button is incorrect. I am not actually deleting or trashing anything and certainly not a snippet. I am actually removing the reference, so I think an cross might be a better icon.

2) The button under the snippets marked 'Add X snippet' could also be misleading. The question this produces is if I click this will I be able to create a X snippet or simple add another reference. A solution to this is to change the label to read 'Add snippet reference'. 

3) When on a snippet reference section what happens if I want to add a new snippet on the fly?
In the long run it would be nice to have a modal window that loads in the add snippet form, this would preserve the users' workflow context. A quick win would be to add link that opens the correct snippet form in another window.

**Comment by davecranwell** [comment] 2015-01-08 17:31
1) fixed in https://github.com/torchbox/wagtail/commit/6a36ed7f7ed3790784733ee80bdf5ee4587edf2a
2) Will consider
3) Duplicate of #396
4) Will consider, however this is pretty much part of django.
5) duplicate

**Closed by davecranwell** 2015-01-08 17:31 UTC
