### ISSUE TITLE
Add loading spinner and disable state to upload "save" buttons.

### ISSUE THREAD

**Issue by salvadormrf** [torchbox/wagtail#1264] opened 2015-05-04 15:44 UTC
When uploading large files (image or documents), specially when using with remote storages it can takes several seconds. Users don't see any kind of feedback.

On modal chooser, we can disable the save button and display a spinner.

    $('form.document-upload', modal.body).submit(function() {
        var formdata = new FormData(this);
        
        // show loader
        $(this).find(".submit-wrapper").addClass("disabled loading-mask loading");

        $.ajax({
            url: this.action,
            data: formdata,
            processData: false,
            contentType: false,
            type: 'POST',
            dataType: 'text',
            success: function(response){
                modal.loadResponseText(response);
            }
        });

        return false;
    });

**Comment by davecranwell** [comment] 2015-05-05 08:29
Duplicate of https://github.com/torchbox/wagtail/pull/1075

**Closed by davecranwell** 2015-05-05 08:29 UTC

**Comment by SalahAdDin** [comment] 2015-05-24 19:52
I don't understand this.
