### ISSUE TITLE
Improve support for same-page/in-page anchor linking

### ISSUE THREAD

**Issue by ababic** [torchbox/wagtail#2631] opened 2016-05-18 13:46 UTC
It would seem that adding a link to an anchor/section on an internal page is quite tricky using the link tool from the RichText widget.

The 'Internal link' option seems like it should be the right place to do this, but that only allows you to choose a page, and nothing else. 

The 'External link' option has URL validation on it, so adding something like "#jump-to-this-bit" is not possible.

We've gotten around the URL validation on the 'External link' option, by adding the URL of the page before the hash (/section/page/#jump-to-this-heading), but that isn't good, because it presumes the page's URL will stay the same, which it often doesn't. Also, the inability to 'edit' a URL via the current RichText editor makes like difficult when changes do happen (but hopefully that will be resolved alongside the work that's being done to replace hallo.js)

**Comment by gasman** [comment] 2016-05-18 13:58
Duplicate of #1049. (Took me a while to find that ticket, since it manages to not use the word 'anchor' anywhere :-) )

Incidentally, editing a link in rich text is now possible, as of #2417.

**Closed by gasman** 2016-05-18 13:58 UTC
