### ISSUE TITLE
Minor bugs report: styles and npm

### ISSUE THREAD

**Issue by SalahAdDin** [torchbox/wagtail#2357] opened 2016-03-14 22:51 UTC
Hi guys, i want report the next bugs for fix before release 1.4 version:

There is missing a space between work in add collection suggest phrase:
![seleccion_056](https://cloud.githubusercontent.com/assets/5034215/13762157/fdf01f3e-ea0a-11e5-98fa-3a4cc8909dd9.png)
Between 'no' and 'añadir' is missing a space.

`icon-arrow-right-after` doesn't works, i see this in pagination:
![seleccion_057](https://cloud.githubusercontent.com/assets/5034215/13762263/bffe9efc-ea0b-11e5-9de4-c70ed1b5507f.png)
I thiough that this problem could be because right margin, but:
![seleccion_058](https://cloud.githubusercontent.com/assets/5034215/13762261/bff1e1a8-ea0b-11e5-8ed8-c5d587f2b91b.png)
No, it's a problem with the icon class.
![seleccion_059](https://cloud.githubusercontent.com/assets/5034215/13762262/bff2ce06-ea0b-11e5-9636-c1fe8604985d.png)
I verified this putting other icon class and this works.

npm start have a problem with watch script: 
[wagtail npm run logs.txt](https://github.com/torchbox/wagtail/files/172985/wagtail.npm.run.logs.txt)

I don't know if a global package error or a wagtail scripts error, but all other scripts well.

Thank you very much.

**Comment by gasman** [comment] 2016-03-15 16:44
@SalahAdDin Thanks very much for the report!

The missing space in the "add a collection" message was an error in the Spanish translation - I've now fixed this in Transifex.

I can confirm that there's a bug with the `icon-arrow-right-after` class - the 'Next' link on pagination (for example, on `/admin/images/`) no longer has a right arrow next to it. @JoshBarr, it appears that this bug was introduced in https://github.com/torchbox/wagtail/commit/a1a294049519ea9cba24c554ad0c0ab13731b3f1 - please can you investigate?

Re the ENOSPC errors on `npm run`, it looks like this is the fix: https://zach-adams.com/2014/10/fix-grunt-fatal-error-watch-enospc/

**Comment by gasman** [comment] 2016-03-15 17:15
@JoshBarr Never mind, figured it out... the `content: ` attribute in the SCSS was missing some quoting. Fixed in 679df7e985a5735a9ffcf232c4ea7f44f83f42d6, and a713c3061bddc317b8ac71ada06a7dda2630c25e on the stable/1.4.x branch.

**Closed by gasman** 2016-03-15 17:15 UTC

**Comment by JoshBarr** [comment] 2016-03-15 18:16
You're just too quick @gasman! It's annoying that Sass strips quotes on strings when interpolating a variable. I generally avoid doing Sass magic for reasons such as this, but I think in the icons case it saves an enormous amount of typing. Thanks for fixing it.
