### ISSUE TITLE
Fields in GUI shrink exponentially in size as you nest them in StreamField

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1716] opened 2015-09-22 23:12 UTC
![screenshot from 2015-09-22 18 09 24](https://cloud.githubusercontent.com/assets/3639540/10034316/317dabd0-6155-11e5-96a8-a67dda1f264d.png)

The fields in the screenshot should be wider, expanding all the way to the edge. It's because the blocks are nested several times, and each time given a width of 83% of its parent.

Here is the code for that block:

```python
        ('listicle', blocks.StructBlock([
            ('headline', blocks.CharBlock(max_length=100, blank=True)),
            ('list', blocks.ListBlock(blocks.StructBlock([
                ('title', blocks.CharBlock(required=True)),
                ('text', blocks.RichTextBlock(blank=True, required=False))
            ])))
        ], icon='list-ol')),
```

**Comment by alexgleason** [comment] 2015-09-23 01:29
Here is the offending code: https://github.com/torchbox/wagtail/blob/16020af2131d310ecc0a0f23188ff767200e7377/wagtail/wagtailadmin/static_src/wagtailadmin/scss/components/streamfield.scss#L29

I haven't fully comprehended the thinking behind this code yet, but removing that line makes the screenshot above appear correctly.

![listicle](https://cloud.githubusercontent.com/assets/3639540/10036124/911f1d40-6168-11e5-9b92-bfe26d7f9c2e.png)

**Comment by davecranwell** [comment] 2015-09-23 08:22
This is similar to if not a duplicate of #1442, albeit described in different terms.

The space you've extended into on the right is reserved for help text. If you add some, it'll overlay the fields.

Essentially this is a known limitation, although not one we're particularly happy with at present. If you're nested more than one level inside your streamblocks, it may suggest you're not using streamfield wisely. Your use however ought to be supported but isn't entirely, as #1442 sugests.

**Closed by davecranwell** 2015-09-23 08:22 UTC

**Comment by SalahAdDin** [comment] 2015-09-25 02:22
:+1:
