### ISSUE TITLE
wagtailfrontendcache throws an error when a root page is created without a site

### ISSUE THREAD

**Issue by strife25** [torchbox/wagtail#1208] opened 2015-04-17 20:05 UTC
On a new install of wagtail w/ wagtailfrontendcache enabled, I go through the following steps:

1. Go to the admin
2. Delete the default "welcome" page from the database
3. Create a new root page

After I create the new root page, I get the following error:

```
[17/Apr/2015 20:02:28] ERROR [django.request:231] Internal Server Error: /admin/pages/new/pages/genericpage/1/
Traceback (most recent call last):
  File "/Users/jryding/.virtualenvs/cms/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jryding/.virtualenvs/cms/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jryding/.virtualenvs/cms/lib/python2.7/site-packages/wagtail/wagtailadmin/views/pages.py", line 211, in create
    revision.publish()
  File "/Users/jryding/.virtualenvs/cms/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 1141, in publish
    page_published.send(sender=page.specific_class, instance=page.specific)
  File "/Users/jryding/.virtualenvs/cms/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/jryding/.virtualenvs/cms/lib/python2.7/site-packages/wagtail/contrib/wagtailfrontendcache/signal_handlers.py", line 9, in page_published_signal_handler
    purge_page_from_cache(instance)
  File "/Users/jryding/.virtualenvs/cms/lib/python2.7/site-packages/wagtail/contrib/wagtailfrontendcache/utils.py", line 100, in purge_page_from_cache
    logger.info("[%s] Purging URL: %s", backend_name, page.full_url + path[1:])
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Digging into the code, this error is the request of the following line:

```
logger.info("[%s] Purging URL: %s", backend_name, page.full_url + path[1:])
```

This line failes because `page.full_url` is set to `None` when it executes, which results in the line throwing an exception. The new page model is still saved, so I just need to refresh the admin in my browser to get back into a good working state.

**Comment by strife25** [comment] 2015-04-17 20:07
The workaround for this issue is to register the new root page as the root of a new site in Wagtail. When the last root page is deleted, it looks like the Site record is also removed from the system. 

One caveat though is that it seems that this error will still occur when new root pages are created.

**Comment by zerolab** [comment] 2015-04-18 19:19
Hi @strife25,
Thank you for the report. You are hitting the bug described in #687.

Closing this as duplicate. Will work on issuing a warning as proposed in https://github.com/torchbox/wagtail/issues/687#issuecomment-60032801

**Comment by gasman** [comment] 2015-04-18 19:32
I think this is different to #687, although the two are certainly related...

The way that the page/site model is designed makes it possible for a page to have no routable URL. This in itself is not a bug - although it's not something that you'd intentionally want to happen, so it's appropriate to give a warning as per #687.

Nevertheless, a page with no routable URL is still perfectly valid, and wagtailfrontendcache ought to be fixed so that it doesn't break in the presence of such pages.

**Comment by zerolab** [comment] 2015-04-18 19:44
Fair enough.

What is the desired behaviour in this case? Only add `page.full_url` to the purge string when it is not None? Or skip the purge all together?

**Comment by gasman** [comment] 2015-04-18 19:49
I'm not really familiar with wagtailfrontendcache's behaviour, but it seems to me that it would be appropriate to simply skip the page. If a page is not accessible at any URL, then there's no way that it can exist in a front-end cache in the first place.

**Closed** 2015-04-21 15:09 UTC
Labels: Bug
